title: Embed component
context:
  url: /images/4370 CoR barometer content page - EN.png
  srcset: ["/images/4370 CoR barometer content page - EN.png@2x 2x"]
  sizes: ["(max-width: 320px) 280px,max-width: 480px) 440px, 800px"]
  alt: banner alt text