title: Embed component
context:
  url: /images/barometerBanner.png
  srcset: ["/images/barometerBanner.png 320w, /images/barometerBanner.png 480w, /images/barometerBanner.png 800w"]
  sizes: ["(max-width: 320px) 280px,max-width: 480px) 440px, 800px"]
  alt: banner alt text