preview: "@europcompreview"
context:
  nav:
    - label: Home
      url: "/components/preview/europcom"
    - label: Agenda
      url: "/components/preview/europcom--program"
    - label: Contributors
      url: "/components/preview/europcom--speakers"
    - label: FAQ
      url: "/components/preview/europcom--faq"
