preview: "@europcompreview"
context:
  themes:
    - title: "Green"
      description: "Conversations will explore"
      picture: "/images/green.svg"
    - title: "Digital"
      description: "Discussions will reflect"
      picture: "/images/digital.svg"
    - title: "Citizens"
      description: "Discussions will focus on the roles"
      picture: "/images/citizens.svg"
