preview: "@europcompreview"
context:
  themes:
    - title: "Green"
      description: "Elit cillum sunt esse reprehenderit ut aute anim ullamco reprehenderit aliquip Lorem cupidatat veniam amet."
      picture: "/images/green.svg"
    - title: "Digital"
      description: "Elit cillum sunt esse reprehenderit ut aute anim ullamco reprehenderit aliquip Lorem cupidatat veniam amet."
      picture: "/images/digital.svg"
    - title: "Citizens"
      description: "Elit cillum sunt esse reprehenderit ut aute anim ullamco reprehenderit aliquip Lorem cupidatat veniam amet."
      picture: "/images/citizens.svg"
