title: Plenaries layout
preview: "@preview"
context:
  title: "141th Plenary session"
  firstparagraph: "The m​embers of the European Committee of the Regions will meet remotely for the 141st plenary session on 8, 9 and 10 December​ 2020."
  tableOfContent: ["Introduction", "Webstreaming" ,"Opinions (48)", "Agenda", "Related press releases (58)"]


