title: Plenary layout
preview: "@preview"
context:
  title: "Plenary sessions"
  firstparagraph: "The European Committee of the Regions (CoR) holds up to 6 plenary sessions each year. Plenary sessions gather CoR members (or alternates) coming from regions and cities from all 27​ EU countries."
  navcontents: ["Introduction", "Previous plenary sessions", "contact"]

