title: Plenaries layout
preview: "@preview"
variants:
  - name: "plenaries"
    context:
      title: "Plenary sessions"
      firstparagraph: "The European Committee of the Regions (CoR) holds up to 6 plenary sessions each year. Plenary sessions give the opportunity for CoR Members (or Alternates) to voice their opinions on EU law that may have an impact on regions and cities in the 27 EU countries."
      tableOfContent: ["Introduction", "Previous plenary sessions", "contact"]
  - name: "archives"
    context:
      title: "Plenary sessions Archive"
      firstparagraph: "The European Committee of the Regions (CoR) holds up to 6 plenary sessions each year. Plenary sessions give the opportunity for CoR Members (or Alternates) to voice their opinions on EU law that may have an impact on regions and cities in the 27 EU countries."
      tableOfContent: ["Introduction", "Previous plenary sessions", "contact"]
  - name: "plenary"
    context:
      title: "141th Plenary session"
      firstparagraph: "The m​embers of the European Committee of the Regions will meet remotely for the 141st plenary session on 8, 9 and 10 December​ 2020."
      tableOfContent: ["Introduction", "Webstreaming" ,"Opinions (48)", "Agenda", "Related press releases (58)"]


