title: Europcom layout
preview: "@europcompreview"
context:
  speakers:
    - name: "Jane Doe"
      title: "Baker at XYZ sprl"
      picture: "http://via.placeholder.com/640x360"
    - name: "Jane Doe"
      title: "Baker at XYZ sprl"
      picture: "http://via.placeholder.com/640x360"
    - name: "Jane Doe"
      title: "Baker at XYZ sprl"
      picture: "http://via.placeholder.com/640x360"
    - name: "Jane Doe"
      title: "Baker at XYZ sprl"
      picture: "http://via.placeholder.com/640x360"
    - name: "Jane Doe"
      title: "Baker at XYZ sprl"
      picture: "http://via.placeholder.com/640x360"
  themes:
    - title: "Green"
      description: "Elit cillum sunt esse reprehenderit ut aute anim ullamco reprehenderit aliquip Lorem cupidatat veniam amet."
    - title: "Digital"
      description: "Elit cillum sunt esse reprehenderit ut aute anim ullamco reprehenderit aliquip Lorem cupidatat veniam amet."
    - title: "Citizens"
      description: "Elit cillum sunt esse reprehenderit ut aute anim ullamco reprehenderit aliquip Lorem cupidatat veniam amet."