title: Table of content
variants:
  - name: default
    context:
      title: Contents
      aria: Content
      tableOfContent: ["Introduction", "Next session", "Previous plenary sessions", "Document", "Contact"]
  - name: documents
    context:
      modifier: documents
      title: Documents
      aria: Documents
      tableOfContent: ["Meetings calendar 2020", "Meetings documents"]
