context:
  title: "Webstreaming of the 141th CoR plenary session "
  description: "Get the Interactio app for simultaneous interpretation, overflow audiences, poster sessions, silent conferences & more. You simply need a laptop and a smartphone (or a tablet)."